const SEARCH_USERS = 'SEARCH_USERS'
const GET_USER = 'GET_USER'
const CLEAR_USERS = 'CLEAR_USERS'
 const SET_LOADING = 'SET_LOADING'
const SET_ALERT = 'SET_ALERT'
const REMOVE_ALERT = 'REMOVE_ALERT'
 const GET_REPOS = 'GET_REPOS'

 export {
   SEARCH_USERS, GET_USER, CLEAR_USERS, SET_LOADING, SET_ALERT, REMOVE_ALERT, GET_REPOS
 }
